[tool.poetry]
name = "meu_projeto"
version = "0.1.0"
description = "Um projeto simples em Python"
authors = ["Seu Nome <seu@email.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
